# Generated by Django 3.1.2 on 2020-11-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201105_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
